import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'tailwindcss/tailwind.css';
import type { AppProps } from 'next/app';
import { Poppins } from 'next/font/google';

const inter = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // or any other valid weight value
});

export const metadata: Metadata = {
  title: 'Penilain Kinerja Guru',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang='en' className='scroll-smooth'>
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
